# This file was generated by liblab | https://liblab.com/

from ups_landedcost_client import UpsLandedcostClient, Environment
from ups_landedcost_client.models import LandedCostRequest

sdk = UpsLandedcostClient(
    username="YOUR_USERNAME",
    password="YOUR_PASSWORD",
    base_url=Environment.DEFAULT.value,
)

request_body = LandedCostRequest(
    currency_code="USD, CAD, EUR",
    trans_id="LCUAT20220208053048_197985278292494",
    allow_partial_landed_cost_result=True,
    alversion="1, 2, 3",
    shipment={
        "id_": "fugiat ullamco ex officia Ut",
        "import_country_code": "US, MX, CA",
        "import_province": "Alberta, Ontario, North Frontier Zone",
        "ship_date": "2022-02-28",
        "incoterms": "FOB, CFR",
        "export_country_code": "DE, CN, JP",
        "trans_modes": "dolore",
        "transport_cost": 100.6,
        "shipment_type": "Duis voluptate sint eiusmo",
        "shipment_items": [
            {
                "commodity_id": "velit dolor adipisicing ipsum cillum",
                "gross_weight": 10.34,
                "gross_weight_unit": "KG",
                "price_each": 346.32,
                "commodity_currency_code": "USD, CAD, EUR",
                "quantity": 0,
                "uom": "KILOGRAM, BAG",
                "hs_code": "0901.90.00.10",
                "description": "sit veniam",
                "origin_country_code": "US, CA, JP, MX",
            }
        ],
    },
)

result = sdk.landedcost.landed_cost(
    request_body=request_body,
    version="v1",
    trans_id="transId",
    transaction_src="testing",
    account_number="AccountNumber",
)

print(result)
